use sparse file when copying VM images around

diff --git a/drivers/kvm_rocks/boot b/drivers/kvm_rocks/boot
--- a/drivers/kvm_rocks/boot
+++ b/drivers/kvm_rocks/boot
@@ -76,12 +76,14 @@ echo Destination disk path is $container:$disk_path
 
 if [ "$container" = "$localhost" ];then
 	echo dd if=$temp_disk_path of=$disk_path bs=1M
-	dd if=$temp_disk_path of=$disk_path bs=1M \
+	cp "$temp_disk_path" "$disk_path" \
 		|| error "unable to copy the disk image $temp_disk_path to $disk_path"
 else
 	echo scp $temp_disk_path $container:$disk_path
-	scp $temp_disk_path $container:$disk_path \
-		|| error "unable to copy the disk image $temp_disk_path to $container:$disk_path"
+	#scp $temp_disk_path $container:$disk_path \
+	#	|| error "unable to copy the disk image $temp_disk_path to $container:$disk_path"
+	ssh $container cp "$temp_disk_path" "$disk_path" \
+                || error "unable to copy the disk image $temp_disk_path to $disk_path on $container"
 fi
 
 # do not install just boot the system as it is
