drivers: first take at the new format of the drivers

diff --git a/drivers/kvm_rocks/boot b/drivers/kvm_rocks/boot
--- a/drivers/kvm_rocks/boot
+++ b/drivers/kvm_rocks/boot
@@ -7,9 +7,8 @@
 # For info see README
 
 
-
-if [ "x$#" != "x3" ]; then
-    echo "This script should be invoked with 3 arguments"
+if [ "x$#" != "x5" ]; then
+    echo "This script should be invoked with 5 arguments"
     exit 1
 fi
 
@@ -20,18 +19,66 @@ function error(){
 
 # tree required arguments
 temp_disk_path=$1
-# unused
-xml_file_path=$2
-hostname=$3
+fqdn=$2
+temp_directory=$3
+vc_out_filepath=$4
+ssh_key=$5
+
 
 # get the path to this script
 pushd `dirname $0` > /dev/null
 SCRIPTPATH=`pwd`
 popd > /dev/null
 
+
+#
+#    ----------------       fixing the disk image  -------------------
+#
+tmp_folder=`mktemp -d`
+
+gw=`echo "cat /vc/frontend/public/@gw" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+fqdn=`echo "cat /vc/frontend/public/@fqdn" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+ip=`echo "cat /vc/frontend/public/@ip" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+netmask=`echo "cat /vc/frontend/public/@netmask" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+public_mac=`echo "cat /vc/frontend/public/@mac" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+private_mac=`echo "cat /vc/frontend/private/@mac" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+dns=`echo "cat /vc/network/dns/@ip" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
+
+guestmount -a $temp_disk_path -m /dev/sda1 $tmp_folder || error "unable to mount guest FS"
+
+# create the net_conf.conf
+cat >> $tmp_folder/root/net_conf.conf << EOF
+public_ip="$ip"
+netmask="$netmask"
+gw="$gw"
+dns="$dns"
+fqdn="$fqdn"
+#use these two entries to specify new mac addresses
+private_mac="$private_mac"
+public_mac="$public_mac"
+EOF
+
+#copy the ssh key
+cat $ssh_key >> $tmp_folder/root/.ssh/authorized_keys
+
+# copy the vc-out.xml
+cp $vc_out_filepath $tmp_folder/root/
+
+# remove udev old network rules
+rm -f $tmp_folder/etc/udev/rules.d/70-persistent-net.rules
+rm -f $tmp_folder/etc/sysconfig/network-scripts/ifcfg-eth0
+rm -f $tmp_folder/etc/sysconfig/network-scripts/ifcfg-eth1
+
+fusermount -u $tmp_folder || error "unable to unmount $tmp_folder"
+rmdir $tmp_folder
+
+
+#
+#    ----------------       deploying disk image and booting  -------------------
+#
 # match everything except 'HOST' and a line of -----
-container=`rocks list host vm $hostname | awk '{if (! /---*/ && ! /HOST/) print $5}'`
-disk_path=`rocks list host vm $hostname showdisks=1 | awk ' {if (/file/) print $7}'`
+container=`rocks list host vm $fqdn | awk '{if (! /---*/ && ! /HOST/) print $5}'`
+disk_path=`rocks list host vm $fqdn showdisks=1 | awk ' {if (/file/) print $7}'`
 # remove useless stuff from file path
 disk_path=${disk_path#file:}
 disk_path=${disk_path/,*/}
@@ -41,16 +88,14 @@ localhost=`hostname -s`
 echo Destination disk path is $container:$disk_path
 
 if [ "$container" == "$localhost" ];then
-	mv $temp_disk_path $disk_path \
+	dd $temp_disk_path $disk_path \
 		|| error "unable to copy the disk image $temp_disk_path to $disk_path"
 else
 	scp $temp_disk_path $container:$disk_path \
 		|| error "unable to copy the disk image $temp_disk_path to $container:$disk_path"
-	rm $disk_path
 fi
 
 # do not install just boot the system as it is
-rocks set host boot $hostname action=os
-rocks start host vm $hostname
-
+rocks set host boot $fqdn action=os
+rocks start host vm $fqdn
 
diff --git a/drivers/kvm_rocks/fix_images b/drivers/kvm_rocks/fix_images
--- a/drivers/kvm_rocks/fix_images
+++ b/drivers/kvm_rocks/fix_images
@@ -16,44 +16,69 @@ function error(){
     exit 1
 }
 
+function uncompress(){
+    #TODO check if the image is really gzipped
+    echo Uncompressing $1
+    gunzip -c "$1" > "$2" || error "Unable to uncompress virtual image"
+}
+
 # tree required arguments
-xml_file=$1
-interfaces=$2
-temp_path=$3
+vc_in=$1
+temp_path=$2
+node_type=$3 # not used at the moment
 
 
-# creating the pool
-transferpool_path=`mktemp -d -p $temp_path`
-transferpool_name="transferimages"
-virsh  pool-create-as $transferpool_name dir --target $transferpool_path
+base_path=`dirname $vc_in`
 
-# creating network mapping file
-v2v_conf=virt-v2v.xml
-echo " <virt-v2v>" > $v2v_conf
-for i in `echo $interfaces|tr ',' ' '`;do 
-	echo "<network type='bridge' name='$i'><network type='bridge' name='$i'/></network>" >> $v2v_conf;
-done
-echo "</virt-v2v>" >> $v2v_conf
+fe_disk_path=`echo "cat /vc/frontend/domain/devices/disk/source/@file" | xmllint --shell $vc_in | grep = | awk -F \" '{print $2}'`
+fe_source_disk=$base_path/$fe_disk_path
 
+uncompress "$fe_source_disk" "$temp_path/${fe_disk_path%.gz}"
+
+comp_disk_path=`echo "cat /vc/compute/domain/devices/disk/source/@file" | xmllint --shell $vc_in | grep = | awk -F \" '{print $2}'`
+comp_source_disk=$base_path/$comp_disk_path
+
+uncompress "$comp_source_disk" "$temp_path/${comp_disk_path%.gz}"
+
+
+
+
+
+
+
+# old virt-v2v stuff
+## creating the pool
+#transferpool_path=`mktemp -d -p $temp_path`
+#transferpool_name="transferimages"
+#virsh  pool-create-as $transferpool_name dir --target $transferpool_path
 #
-# running vrit-v2v
+## creating network mapping file
+#v2v_conf=virt-v2v.xml
+#echo " <virt-v2v>" > $v2v_conf
+#for i in `echo $interfaces|tr ',' ' '`;do 
+#	echo "<network type='bridge' name='$i'><network type='bridge' name='$i'/></network>" >> $v2v_conf;
+#done
+#echo "</virt-v2v>" >> $v2v_conf
 #
-echo "virt-v2v  -f $v2v_conf -f /var/lib/virt-v2v/virt-v2v.db -i libvirtxml -oa sparse -os $transferpool_name \
-		$xml_file  2>&1  || error Failed to execute virt-v2v"
-virt-v2v  -f $v2v_conf -f /var/lib/virt-v2v/virt-v2v.db -i libvirtxml -oa sparse -os $transferpool_name \
-		$xml_file  2>&1  || error "Failed to execute virt-v2v\nDelete transfer pool manually virsh pool-destroy $transferpool_name."
-
-# get the xml from libvirt
-domain_name=`echo "cat //domain/name" | xmllint --shell $xml_file | sed '/^\/ >/d' | sed 's/<[^>]*.//g'`
-virsh dumpxml $domain_name > $xml_file || error "Unable to dump domaind xml."
-virsh undefine $domain_name || error "Unable to undefine the domain."
-
-# removing the pool
-disk_filename=`ls $transferpool_path`
-mv $transferpool_path/$disk_filename $temp_path || error "Unable to rename the file $disk_filename\nDelete it manually\nvirsh pool-destroy $transferpool_name."
-virsh pool-destroy $transferpool_name || error "Unable to delete $transferpool_name pool.\nDelete it manually\nvirsh pool-destroy $transferpool_name."
-#virsh pool-undefine $transferpool_name || error "Unable to delete $transferpool_name pool.\nDelete it manually."
-
-rmdir $transferpool_path
-rm $v2v_conf
+##
+## running vrit-v2v
+##
+#echo "virt-v2v  -f $v2v_conf -f /var/lib/virt-v2v/virt-v2v.db -i libvirtxml -oa sparse -os $transferpool_name \
+#		$xml_file  2>&1  || error Failed to execute virt-v2v"
+#virt-v2v  -f $v2v_conf -f /var/lib/virt-v2v/virt-v2v.db -i libvirtxml -oa sparse -os $transferpool_name \
+#		$xml_file  2>&1  || error "Failed to execute virt-v2v\nDelete transfer pool manually virsh pool-destroy $transferpool_name."
+#
+## get the xml from libvirt
+#domain_name=`echo "cat //domain/name" | xmllint --shell $xml_file | sed '/^\/ >/d' | sed 's/<[^>]*.//g'`
+#virsh dumpxml $domain_name > $xml_file || error "Unable to dump domaind xml."
+#virsh undefine $domain_name || error "Unable to undefine the domain."
+#
+## removing the pool
+#disk_filename=`ls $transferpool_path`
+#mv $transferpool_path/$disk_filename $temp_path || error "Unable to rename the file $disk_filename\nDelete it manually\nvirsh pool-destroy $transferpool_name."
+#virsh pool-destroy $transferpool_name || error "Unable to delete $transferpool_name pool.\nDelete it manually\nvirsh pool-destroy $transferpool_name."
+##virsh pool-undefine $transferpool_name || error "Unable to delete $transferpool_name pool.\nDelete it manually."
+#
+#rmdir $transferpool_path
+#rm $v2v_conf
 
